name: cricket_player_manager
description: A Flutter cricket player management app using Back4App

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  parse_server_sdk_flutter: ^7.0.0
  image_picker: ^1.0.7
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
